/**
 * A corrupt rate in the snapshot must not become a "measured" price (#5328).
 *
 * `loadModelsDevSnapshot` checked only `version === 1` and
 * `Array.isArray(entries)`, then did `parsed.entries as ModelEntry[]` — with an
 * in-line rationale that the file is generated by our own script, so Zod
 * re-validation is unnecessary.
 *
 * The rationale is reasonable and this does NOT overturn it wholesale. What it
 * does is match the sibling tier of the SAME pricing chain:
 * `models-generated-loader.ts:120` already type-checks `inputPer1M` /
 * `outputPer1M` before accepting pricing, and `manifest-overlay.ts:315`
 * `safeParse`s per entry. Two of the three tiers validate their rates; this was
 * the third.
 *
 * It matters because the value does not stay local. Entries reach
 * `getDefaultRegistry().getEntry()`, and `usage-log.ts:129` passes
 * `entry.pricing.inputPer1M` into `computeTokenCost` and records
 * `priced: true` — so a string or null rate yields a `NaN` or concatenated cost
 * labelled as a MEASURED figure. That is precisely the `priced: false` vs real-$0
 * distinction #4165 exists to protect.
 *
 * The fix strips malformed pricing rather than dropping the entry, mirroring
 * the sibling's `return undefined` for pricing alone: a model with a corrupt
 * rate becomes an unpriced model, which the cost chain already handles honestly.
 * Dropping the entry would silently shrink the catalog instead.
 *
 * @module config/models-dev-snapshot-pricing.test
 */

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import { loadModelsDevSnapshot } from './models-dev-snapshot-loader.js';

let tempDir: string;

function snapshotWith(entries: unknown[]): string {
  const path = join(tempDir, 'snap.json');
  writeFileSync(path, JSON.stringify({ version: 1, entries }), 'utf-8');
  return path;
}

function entry(id: string, extra: Record<string, unknown> = {}): Record<string, unknown> {
  return { id, vendor: 'acme', family: 'acme-1', ...extra };
}

beforeEach(() => {
  tempDir = mkdtempSync(join(tmpdir(), 'snap-pricing-'));
});
afterEach(() => {
  rmSync(tempDir, { recursive: true, force: true });
});

describe('snapshot pricing validation (#5328)', () => {
  it('keeps an entry with valid pricing, pricing intact', () => {
    const path = snapshotWith([entry('a', { pricing: { inputPer1M: 0.2, outputPer1M: 0.4 } })]);
    const result = loadModelsDevSnapshot({ path });

    expect(result.status).toBe('loaded');
    expect(result.entries).toHaveLength(1);
    expect(result.entries[0]?.pricing).toEqual({ inputPer1M: 0.2, outputPer1M: 0.4 });
  });

  it('keeps an entry that legitimately has no pricing', () => {
    // 15 of the 353 committed entries carry no pricing at all. Treating absent
    // pricing as corruption would drop real models from the catalog.
    const path = snapshotWith([entry('b')]);
    const result = loadModelsDevSnapshot({ path });

    expect(result.entries).toHaveLength(1);
    expect(result.entries[0]?.pricing).toBeUndefined();
  });

  it('strips pricing whose inputPer1M is not a number, keeping the entry', () => {
    // The defect: this rate reached computeTokenCost and was recorded with
    // priced: true. Stripping it makes the model honestly unpriced instead.
    const path = snapshotWith([entry('c', { pricing: { inputPer1M: '0.2', outputPer1M: 0.4 } })]);
    const result = loadModelsDevSnapshot({ path });

    expect(result.entries).toHaveLength(1);
    expect(result.entries[0]?.pricing).toBeUndefined();
  });

  it('strips pricing whose outputPer1M is null', () => {
    const path = snapshotWith([entry('d', { pricing: { inputPer1M: 0.2, outputPer1M: null } })]);
    const result = loadModelsDevSnapshot({ path });

    expect(result.entries).toHaveLength(1);
    expect(result.entries[0]?.pricing).toBeUndefined();
  });

  it('does not strip pricing from the good entries beside a bad one', () => {
    // The pair. A fix that stripped everything would satisfy the tests above
    // and quietly unprice the whole catalog.
    const path = snapshotWith([
      entry('good', { pricing: { inputPer1M: 1, outputPer1M: 2 } }),
      entry('bad', { pricing: { inputPer1M: 'x', outputPer1M: 2 } }),
    ]);
    const result = loadModelsDevSnapshot({ path });

    expect(result.entries).toHaveLength(2);
    expect(result.entries.find((e) => e.id === 'good')?.pricing).toEqual({
      inputPer1M: 1,
      outputPer1M: 2,
    });
    expect(result.entries.find((e) => e.id === 'bad')?.pricing).toBeUndefined();
  });

  it('still loads the committed snapshot with its pricing intact', () => {
    // The regression guard that matters: every test above uses a fixture, so
    // all of them would stay green if the real snapshot stopped loading.
    const result = loadModelsDevSnapshot();
    expect(result.status).toBe('loaded');
    expect(result.entries.filter((e) => e.pricing !== undefined).length).toBeGreaterThan(300);
  });
});
