/**
 * Skills module exports (Voyager-style skill library) - Issue #528
 * Split from agents.ts for file size compliance (Issue #285)
 */

export {
  // Types
  type Skill,
  type SkillWithMetrics,
  type SkillParameter,
  type SkillExample,
  type SkillExecution,
  type SkillMetrics,
  type SkillQuery,
  type SkillSearchResult,
  type CreateSkillOptions,
  type SkillCompositionRequest,
  type SkillComposition,
  type CompositionStep,
  type InputBinding,
  type SkillLibraryConfig,
  type SkillComplexity,
  type SkillExecutionStatus,
  type SkillCategory,
  type LibraryStatistics,
  type SkillStore,
  type SkillComposerConfig,
  type CompositionValidation,
  type RecordExecutionOptions,
  // Security types (Issue #374)
  type SkillPermission,
  type SkillCapabilities,
  type SkillRBAC,
  type SkillProvenance,
  type SkillAttestation,
  type AuthorizationMethod,
  type SecurityErrorCode,
  type SkillSecurityError,
  // Dependency graph types
  type SkillDependency,
  type SkillDependencyType,
  type DependencyError,
  type DependencyErrorCode,
  type ISkillDependencyGraph,
  // Skill loader types
  type SkillLoaderConfig,
  type SkillLoaderError,
  type SkillLoaderErrorCode,
  type LoadedSkillSet,
  type RoleSkillMapping,
  type FallbackBehavior,
  type ISkillLoader,
  // Constants
  DEFAULT_SKILL_LIBRARY_CONFIG,
  COMPLEXITY_ORDER,
  DEFAULT_COMPOSER_CONFIG,
  SKILL_PERMISSIONS,
  DEFAULT_PERMISSIONS,
  MAX_EXECUTION_TIME_MS,
  DEFAULT_EXECUTION_TIME_MS,
  DEFAULT_CAPABILITIES as SKILL_DEFAULT_CAPABILITIES,
  DEFAULT_RBAC,
  DEFAULT_ROLE_MAPPINGS,
  DEFAULT_SKILL_LOADER_CONFIG,
  // Schemas
  SkillPermissionSchema,
  AgentRoleSchema as SkillAgentRoleSchema,
  SkillCapabilitiesSchema,
  SkillRBACSchema,
  SkillProvenanceSchema,
  AuthorizationMethodSchema,
  SkillAttestationSchema,
  SecurityErrorCodeSchema,
  SkillSecurityErrorSchema,
  SkillDependencyTypeSchema,
  SkillDependencySchema,
  DependencyErrorCodeSchema,
  DependencyErrorSchema,
  SkillLoaderConfigSchema,
  LoadedSkillSetSchema,
  SkillLoaderErrorSchema,
  // Classes
  SkillLibrary,
  SkillComposer,
  SkillDependencyGraph,
  SkillLoader,
  // Factory functions
  createSkillLibrary,
  createSkillComposer,
  createDependencyError,
  buildDependencyGraph as buildSkillDependencyGraph,
  resolveWithFallbacks,
  findMissingDependencies,
  createSkillDependencyGraph,
  createSkillLoader,
  // Security functions
  canExecuteSkill,
  createAttestation,
  validateSkillProvenance,
  checkPermissionBoundary,
  createSecurityError,
  validateCapabilities as validateSkillCapabilities,
  validateRBAC as validateSkillRBAC,
  validateSkillExecution,
  // Integration hooks
  initializeAgentSkills,
  getSkillsForTask,
  getSkillSetForTask,
} from '../agents/index.js';
