/**
 * Agents exports - Agent framework, TechLead, Experts
 * Split from index.ts for file size compliance (Issue #285)
 */

export {
  // Base agent
  BaseAgent,
  TaskSchema,
  AgentMessageSchema,
  BaseAgentOptionsSchema,
  type BaseAgentOptions,
  // Simple agent
  SimpleAgent,
  // TechLead
  TechLead,
  createTechLead,
  type ExecutionPlan,
  // TechLead types
  type SubTask,
  type TaskAnalysis,
  type ExpertAssignment,
  type SynthesizedResult,
  type ResultSummary,
  type Conflict,
  type TechLeadOptions,
  type SubtaskPriority,
  type SubtaskStatus,
  SubTaskSchema,
  TaskAnalysisSchema,
  ExpertAssignmentSchema,
  SynthesizedResultSchema,
  TechLeadOptionsSchema,
  SubtaskPrioritySchema,
  SubtaskStatusSchema,
  EXPERT_CAPABILITIES,
  TASK_TYPE_EXPERTS,
  // State machine
  AgentStateMachine,
  createStateMachine,
  type StateTransitionEvent,
  type StateTransition,
  type StateChangeCallback,
  type TransitionErrorCallback,
  type StateMachineOptions,
  // Context management
  ContextManager,
  ContentPriority,
  DEFAULT_BUDGET,
  ContextBudgetSchema,
  ContextManagerConfigSchema,
  type ContextBudget,
  type ContextItem,
  type ContextManagerConfig,
  type ContextStats,
  // Context pruning
  ContextPruner,
  PruningStrategy,
  ContextPrunerConfigSchema,
  type ContextPrunerConfig,
  type PruneOptions,
  type PruneResult,
  // Expert system
  type ExpertConfig,
  type ModelPreference,
  type BuiltInExpertType,
  ExpertConfigSchema,
  ModelPreferenceSchema,
  BuiltInExpertTypeSchema,
  BUILT_IN_EXPERTS,
  EXPERT_TYPE_TO_ROLE,
  validateExpertConfig,
  safeValidateExpertConfig,
  ExpertFactory,
  Expert,
  FactoryError,
  type CreateExpertOptions,
  ExpertRegistry,
  RegistryError,
  getExpertRegistry,
  type RegisterOptions as ExpertRegisterOptions,
  type QueryOptions,
  type RegistryStats,
  // Task analysis
  analyzeTask,
  TaskDomain,
  TaskComplexity,
  AnalysisError,
  TaskAnalysisResultSchema,
  type TaskAnalysisResult,
  // Expert selection
  selectExperts,
  quickSelect,
  createDefaultRegistry,
  SelectionError,
  ExpertCollaborationPattern,
  type ExpertCollaborationPatternType,
  ScoreBreakdownSchema,
  ExpertMatchSchema,
  SelectionResultSchema,
  SelectionOptionsSchema,
  type ExpertDefinition,
  type ExpertMatch,
  type ScoreBreakdown,
  type SelectionResult,
  type SelectionOptions,
  type SelectionExpertRegistry,
  // Expert types
  type ExpertDomain,
  type ExpertOptions,
  type ExpertOutput,
  type CodeAnalysisResult,
  type CodeChange,
  type SecurityAnalysisResult,
  type Vulnerability,
  type ComplianceStatus,
  type ArchitectureAnalysisResult,
  type ArchitecturePattern,
  type ArchitectureDecision,
  type SystemComponent,
  type TestingAnalysisResult,
  type GeneratedTest,
  type CoverageMetrics,
  type TestQuality,
  type DocumentationResult,
  type DocumentationSection,
  type ApiDocumentation,
  type ApiEndpoint,
  type ApiType,
  ExpertDomainSchema,
  ExpertOptionsSchema,
  ExpertOutputSchema,
  VulnerabilitySeveritySchema,
  VulnerabilitySchema,
  CodeChangeSchema,
  GeneratedTestSchema,
  CoverageMetricsSchema,
  EXPERT_DEFAULT_TEMPERATURES,
  EXPERT_DEFAULT_CAPABILITIES,
  // Specialized experts
  CodeExpert,
  createCodeExpert,
  type CodeExpertOptions,
  SecurityExpert,
  createSecurityExpert,
  type SecurityExpertOptions,
  type SecurityFocusArea,
  ArchitectureExpert,
  createArchitectureExpert,
  type ArchitectureExpertOptions,
  type ArchitectureStyle,
  type QualityAttribute,
  TestingExpert,
  createTestingExpert,
  type TestingExpertOptions,
  DocumentationExpert,
  createDocumentationExpert,
  type DocumentationExpertOptions,
  // Collaboration
  type CollaborationPattern,
  type SessionStatus,
  type VoteDecision,
  type CollaborationConfig,
  type ExpertParticipation,
  type CollaborationMessage,
  type TaskAssignmentMessage,
  type ResultSubmissionMessage,
  type ReviewRequestMessage,
  type ReviewResponseMessage,
  type FeedbackMessage,
  type VoteMessage,
  type StatusUpdateMessage,
  type SessionState,
  type CollaborationResult,
  type ExpertResultSummary,
  type AggregatedResult,
  type ResultConflict,
  type AggregationMetadata,
  CollaborationPatternSchema,
  SessionStatusSchema,
  VoteDecisionSchema,
  CollaborationConfigSchema,
  ExpertParticipationSchema,
  VoteMessageSchema,
  ReviewResponseMessageSchema,
  DEFAULT_TIMEOUTS,
  DEFAULT_MAX_RETRIES,
  MIN_EXPERTS_FOR_PATTERN,
  CollaborationSession,
  createCollaborationSession,
  type CollaborationSessionOptions,
  type SessionEvent,
  SequentialProtocol,
  ParallelProtocol,
  ReviewProtocol,
  ConsensusProtocol,
  ProtocolFactory,
  createProtocolFactory,
  type ICollaborationProtocol,
  type ProtocolOptions,
  ResultAggregator,
  createResultAggregator,
  aggregateResults,
  type AggregationStrategy,
  type AggregatorOptions,
  type AggregatorInput,
  type ExpertResult,
  type ConflictResolver,
  type QualityScorer,
  // Observability (OrchestrationObserver - renamed from SwarmObserver in Issue #251)
  AgentStateSchema,
  OrchestrationObserverConfigSchema,
  ObserverTopics,
  type AgentState as ObserverAgentState,
  type TrackedAgent,
  type RoutingDecision,
  type TokenUsage as ObserverTokenUsage,
  type CostMetrics,
  type SessionMetrics,
  type OrchestrationStats,
  type OrchestrationObserverEvent,
  type OrchestrationObserverListener,
  type OrchestrationObserverConfig,
  type OrchestrationObserverOptions,
  type IOrchestrationObserver,
  OrchestrationObserver,
  createOrchestrationObserver,
} from '../agents/index.js';

// Backward compatibility aliases (deprecated, will be removed in v3.0)
/* eslint-disable @typescript-eslint/no-deprecated */
export {
  SwarmObserverConfigSchema,
  type SwarmStats,
  type SwarmObserverEvent,
  type SwarmObserverListener,
  type SwarmObserverConfig,
  type SwarmObserverOptions,
  type ISwarmObserver,
  SwarmObserver,
  createSwarmObserver,
} from '../agents/index.js';
/* eslint-enable @typescript-eslint/no-deprecated */
