/**
 * nexus-agents config init command
 *
 * Generates a starter configuration file with sensible defaults.
 *
 * (Source: Issue #65, PROJECT_PLAN.md Section 5.2)
 */

import { existsSync } from 'node:fs';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { getErrorMessage } from '../core/index.js';
import { colors } from './ansi-output.js';

/**
 * Config init options.
 */
export interface ConfigInitOptions {
  /** Output file path */
  readonly output?: string;
  /** Force overwrite existing file */
  readonly force?: boolean;
}

/**
 * Result of config init operation.
 */
export interface ConfigInitResult {
  readonly success: boolean;
  readonly path: string;
  readonly message: string;
  readonly created: boolean;
}

/**
 * Default configuration file name.
 */
const DEFAULT_CONFIG_FILE = 'nexus-agents.yaml';

/**
 * Generated YAML configuration template with comments.
 */
const CONFIG_TEMPLATE = `# Nexus Agents Configuration
# Generated by: nexus-agents config init
# Documentation: https://github.com/williamzujkowski/nexus-agents

# Model configuration
models:
  # Default model for general tasks
  default: claude-sonnet-4

  # Model tiers for capability-matched routing
  tiers:
    # Fast: Quick responses, lower cost
    fast:
      - claude-haiku-3
      - gpt-4o-mini
      - gemini-flash

    # Balanced: Good quality and speed (recommended for most tasks)
    balanced:
      - claude-sonnet-4
      - gpt-4o
      - gemini-pro

    # Powerful: Complex reasoning, highest quality
    powerful:
      - claude-opus-4
      - o1-pro
      - gemini-ultra

  # Provider-specific configuration (optional)
  # providers:
  #   anthropic:
  #     timeout: 60000
  #     maxRetries: 3
  #   openai:
  #     timeout: 30000
  #     maxRetries: 2

# Expert configuration
experts:
  # Enable built-in experts (code, architecture, security, docs, testing)
  builtin: true

  # Custom expert definitions (optional)
  # custom:
  #   rust_expert:
  #     prompt: |
  #       You are a Rust expert specializing in systems programming,
  #       memory safety, and high-performance code.
  #     tier: powerful
  #     temperature: 0.2
  #
  #   api_expert:
  #     prompt: |
  #       You are an API design expert focusing on REST, GraphQL,
  #       and API security best practices.
  #     tier: balanced
  #     temperature: 0.3

# Workflow configuration
workflows:
  # Directory containing workflow templates
  templatesDir: ./workflows

  # Maximum execution time per workflow (ms)
  timeout: 300000

  # Maximum parallel steps
  maxParallel: 5

# Security configuration
security:
  # Allowed file system paths
  allowedPaths:
    - ./

  # Blocked file patterns (glob)
  blockedPatterns:
    - "**/.env*"
    - "**/credentials*"
    - "**/*.pem"
    - "**/*.key"

  # Rate limiting
  rateLimit:
    enabled: true
    requestsPerMinute: 60

  # Path to secrets file (optional)
  # secretsFile: ./.nexus-secrets.yaml

# Gateway middleware configuration (Issue #896, #897)
# gateway:
#   enabled: true
#   # Per-tool tier overrides (DIRECT, ANALYZED, or ORCHESTRATED)
#   tierOverrides:
#     memory_query: DIRECT
#     delegate_to_model: ANALYZED
#     orchestrate: ORCHESTRATED

# Logging configuration
logging:
  # Log level: debug, info, warn, error
  level: info

  # Output format: json, pretty
  format: json

  # Destination: stdout, stderr, file
  destination: stdout

  # Log file path (required if destination is 'file')
  # filePath: ./logs/nexus-agents.log
`;

/**
 * Resolves the output path for the configuration file.
 */
function resolveOutputPath(output?: string): string {
  if (output !== undefined && output !== '') {
    return resolve(process.cwd(), output);
  }
  return resolve(process.cwd(), DEFAULT_CONFIG_FILE);
}

/**
 * Checks if a file exists at the given path.
 */
function fileExists(path: string): boolean {
  return existsSync(path);
}

/**
 * Ensures the parent directory exists.
 */
async function ensureDirectory(filePath: string): Promise<void> {
  const dir = dirname(filePath);
  if (dir !== '.' && !existsSync(dir)) {
    await mkdir(dir, { recursive: true });
  }
}

/**
 * Writes the configuration file.
 */
async function writeConfigFile(path: string): Promise<void> {
  await ensureDirectory(path);
  await writeFile(path, CONFIG_TEMPLATE, 'utf-8');
}

/**
 * Runs the config init command.
 *
 * @param options - Config init options
 * @returns Result of the operation
 */
export async function runConfigInit(options: ConfigInitOptions = {}): Promise<ConfigInitResult> {
  const outputPath = resolveOutputPath(options.output);

  // Check if file already exists
  if (fileExists(outputPath) && options.force !== true) {
    return {
      success: false,
      path: outputPath,
      message: `File already exists: ${outputPath}. Use --force to overwrite.`,
      created: false,
    };
  }

  try {
    await writeConfigFile(outputPath);

    return {
      success: true,
      path: outputPath,
      message: `Configuration file created: ${outputPath}`,
      created: true,
    };
  } catch (error) {
    const message = getErrorMessage(error);
    return {
      success: false,
      path: outputPath,
      message: `Failed to create configuration file: ${message}`,
      created: false,
    };
  }
}

/**
 * Prints the result of config init.
 */
export function printConfigInitResult(result: ConfigInitResult): void {
  const writeLine = (text: string): void => {
    process.stdout.write(text + '\n');
  };

  writeLine('');

  if (result.success) {
    writeLine(`${colors.green}${colors.bold}Configuration created successfully!${colors.reset}`);
    writeLine('');
    writeLine(`  ${colors.cyan}Path:${colors.reset} ${result.path}`);
    writeLine('');
    writeLine(`${colors.dim}Next steps:${colors.reset}`);
    writeLine(`  1. Edit the configuration file to customize settings`);
    writeLine(`  2. Run ${colors.cyan}nexus-agents${colors.reset} to start the MCP server`);
    writeLine(`  3. Or run ${colors.cyan}nexus-agents doctor${colors.reset} to verify setup`);
  } else {
    writeLine(`${colors.red}${colors.bold}Configuration creation failed${colors.reset}`);
    writeLine('');
    writeLine(`  ${colors.red}Error:${colors.reset} ${result.message}`);
  }

  writeLine('');
}

/**
 * Runs the config init command and prints results.
 * Returns exit code (0 = success, 1 = error).
 */
export async function configInitCommand(options: ConfigInitOptions = {}): Promise<number> {
  const result = await runConfigInit(options);
  printConfigInitResult(result);
  return result.success ? 0 : 1;
}
