/**
 * Synchronous config file generation for setup command.
 *
 * Reuses the CONFIG_TEMPLATE from config-init.ts pattern but provides
 * a synchronous API suitable for the setup command flow.
 *
 * @module cli/setup-config
 * (Source: Issue #1252 - Setup auto-generates nexus-agents.yaml)
 */

import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { getErrorMessage } from '../core/index.js';

/** Default configuration file name. */
const DEFAULT_CONFIG_FILE = 'nexus-agents.yaml';

/** Result of the config generation step. */
export interface ConfigStepResult {
  readonly success: boolean;
  readonly path: string;
  readonly created: boolean;
  readonly message: string;
}

/**
 * Minimal YAML config template for setup command.
 * Intentionally brief — just enough to get started.
 * Users can run `nexus-agents config init` for the full template.
 */
const SETUP_CONFIG_TEMPLATE = `# Nexus Agents Configuration
# Generated by: nexus-agents setup
# Full template: nexus-agents config init

models:
  default: claude-sonnet-4

experts:
  builtin: true

logging:
  level: info
  format: json
`;

/**
 * Generates a nexus-agents.yaml config file synchronously.
 *
 * @param projectRoot - Directory to create config in.
 * @param force - Overwrite existing config.
 * @param dryRun - Report what would happen without writing.
 */
export function runConfigInitSync(
  projectRoot: string,
  force: boolean,
  dryRun: boolean
): ConfigStepResult {
  const outputPath = resolve(projectRoot, DEFAULT_CONFIG_FILE);

  if (existsSync(outputPath) && !force) {
    return {
      success: true,
      path: outputPath,
      created: false,
      message: 'Config already exists (use --force to overwrite)',
    };
  }

  if (dryRun) {
    return {
      success: true,
      path: outputPath,
      created: true,
      message: `Would create: ${outputPath}`,
    };
  }

  try {
    writeFileSync(outputPath, SETUP_CONFIG_TEMPLATE, 'utf-8');
    return {
      success: true,
      path: outputPath,
      created: true,
      message: `Created: ${outputPath}`,
    };
  } catch (error: unknown) {
    return {
      success: false,
      path: outputPath,
      created: false,
      message: `Failed: ${getErrorMessage(error)}`,
    };
  }
}
