/**
 * The signing half of the caller-commits append (#3927 item 4, phase 2;
 * #6257 increment 1).
 *
 * `append-ratification-record.ts` copies a record into the committed ledger;
 * this module signs the COMMITTED copy's hash — after re-sequencing and
 * re-hashing, never before — when a key is configured, resolves that
 * configuration (`--signing-key`, else `NEXUS_VOTE_SIGNING_KEY`, else the
 * dedicated agent key when it exists), and words the one-line notice the
 * script prints either way. The private key is only ever named by path to
 * ssh-keygen; its bytes never enter this process or its output, and the
 * notice names the signer's principal, never the key.
 *
 * ## Which key, and what the signature then says (#6257 panel, option B)
 *
 * Two identities are listed in `governance/allowed_signers`: the owner's key
 * under a human principal, and the autonomous loop's key under
 * `nexus-agent@<host>`. The rule is that the owner's key is RESERVED for
 * records a human appended, so that `signed:owner` on the gate line means
 * a human ran the append and `signed:agent` means the loop did. Two
 * mechanisms hold the rule:
 *
 * - The agent key is the DEFAULT. When neither the flag nor the variable
 *   names a key and `<dataDir>/auth/vote-record-signing.key` exists
 *   (`~/.nexus-agents/auth/…`; generated by `scripts/vote-record-keygen.ts`),
 *   the append signs with it. An automated run needs no configuration to
 *   sign as itself.
 * - A signature that resolves to an OWNER principal is REFUSED unless
 *   `--as-owner` was passed. The flag is the human's attestation; without
 *   it, a run that happened to pick up the owner's key (an inherited
 *   `NEXUS_VOTE_SIGNING_KEY`, a copied shell profile) cannot claim human
 *   presence by accident. The converse — `--as-owner` with a key the file
 *   lists as the agent — is refused too, as a misconfiguration: the record
 *   would say `agent` about a run a human attested to.
 *
 * What this is NOT: host isolation. Both keys live on the operator's host
 * and the agent process can read both; the refusal guards against an
 * ACCIDENTAL owner claim, not a deliberate one. Non-repudiation against a
 * compromised host is a custody question (#6350, CI/OIDC-issued keys for a
 * CI-run append). The threat model and `governance/README.md` say the same.
 *
 * @module scripts/append-ratification-signing
 * (Source: Issue #3927 item 4, #6257)
 */

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import type { SignableLedgerRecord } from '../packages/nexus-agents/src/audit/vote-record-signature.js';
import {
  ALLOWED_SIGNERS_FILE,
  signVoteRecordHash,
  signerKindOf,
} from '../packages/nexus-agents/src/audit/vote-record-signature.js';
import { nexusSharedPath } from '../packages/nexus-agents/src/config/nexus-data-dir.js';

/** The env var naming the signing key when `--signing-key` is not passed. */
export const VOTE_SIGNING_KEY_ENV = 'NEXUS_VOTE_SIGNING_KEY';

/**
 * The dedicated agent signing key's location: `<dataDir>/auth/…`, which is
 * `~/.nexus-agents/auth/vote-record-signing.key` on a normal machine and
 * follows `NEXUS_DATA_DIR` / the sandbox root otherwise. Homedir-scoped on
 * purpose (`nexusSharedPath`): one identity per host, never inside a repo
 * checkout. `scripts/vote-record-keygen.ts` writes it; nothing in this tree
 * reads its bytes.
 */
export function agentSigningKeyPath(): string {
  return nexusSharedPath('auth', 'vote-record-signing.key');
}

/** Where the key came from, for the notice. */
export type SigningKeySource = 'flag' | 'env' | 'agent-default';

/** How the append signs: the key (by path) and the file the signature must verify against. */
export interface SigningOptions {
  /** Private key path, or its `.pub` when the private half is in ssh-agent. Named to ssh-keygen, never read here. */
  readonly keyPath: string;
  /** The allowed_signers the signature is verified against; it also supplies the signer's `keyId`. */
  readonly allowedSignersPath: string;
  /** `--signing-key`, `NEXUS_VOTE_SIGNING_KEY`, or the agent key found at its default path. */
  readonly source: SigningKeySource;
  /**
   * `--as-owner`: the caller attests that a human ran this append, so a
   * signature under an OWNER principal is permitted. Required, not
   * optional, so every call site states which run this is.
   */
  readonly asOwner: boolean;
}

/** Whether the committed record was signed, and why not when it was not. */
export type SigningState = 'signed' | 'unsigned-no-key';

export type SignStep<R extends SignableLedgerRecord = SignableLedgerRecord> =
  | { readonly ok: true; readonly record: R; readonly signing: SigningState }
  /** `detail` is the `signing-failed` refusal text; nothing has been written. */
  | { readonly ok: false; readonly detail: string };

/**
 * Sign the COMMITTED record's hash — the one `relink` just computed — when a
 * key is configured. Every failure is a refusal before any write: an
 * allowed_signers that cannot be read, a key ssh-keygen cannot use, a key the
 * file does not list (a signature no gate could verify is a defect at the
 * moment of signing, not later), and — #6257 — an owner-principal signature
 * from a run that did not pass `--as-owner`, or `--as-owner` on a run whose
 * key the file lists as the agent.
 */
export function signCommitted<R extends SignableLedgerRecord>(
  record: R,
  signing: SigningOptions | undefined
): SignStep<R> {
  if (signing === undefined) return { ok: true, record, signing: 'unsigned-no-key' };
  let allowedSigners: string;
  try {
    allowedSigners = readFileSync(signing.allowedSignersPath, 'utf-8');
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    return {
      ok: false,
      detail:
        `allowed_signers at ${signing.allowedSignersPath} could not be read (${message}); ` +
        'a signature that cannot be verified against the committed file is not written.',
    };
  }
  // #6372: a vote record anchors its signature window at `recordedAt`, a
  // redaction record at `at`; the signed message is the hash either way.
  const signed = signVoteRecordHash({
    hash: record.hash,
    ...('recordedAt' in record ? { recordedAt: record.recordedAt } : { at: record.at }),
    keyPath: signing.keyPath,
    allowedSigners,
  });
  if (!signed.ok) {
    return {
      ok: false,
      detail:
        `could not sign record '${record.id}' with the configured key: ${signed.reason}. ` +
        'Nothing was written; fix the key or omit --signing-key to append unsigned.',
    };
  }
  const mismatch = attestationMismatch(signing, signed.signature.keyId);
  if (mismatch !== undefined) return { ok: false, detail: mismatch };
  return { ok: true, record: { ...record, signature: signed.signature }, signing: 'signed' };
}

/**
 * The #6257 rule, as a refusal text or nothing: an OWNER principal needs
 * `--as-owner`; `--as-owner` needs an owner principal. The two legitimate
 * cells — {owner, attested} and {agent, automated} — return `undefined`.
 */
function attestationMismatch(signing: SigningOptions, principal: string): string | undefined {
  const kind = signerKindOf(principal);
  if (kind === 'owner' && !signing.asOwner) {
    return (
      `the configured key (${describeSource(signing)}) is listed in allowed_signers as OWNER principal ` +
      `'${principal}', and this run did not pass --as-owner. An owner signature attests that a human ` +
      'ran the append; an automated run must sign with the agent key (scripts/vote-record-keygen.ts). ' +
      'Nothing was written. Pass --as-owner if a human is running this.'
    );
  }
  if (kind === 'agent' && signing.asOwner) {
    return (
      `--as-owner was passed, but the configured key (${describeSource(signing)}) is listed in ` +
      `allowed_signers as AGENT principal '${principal}'; the record would attribute a human-attested ` +
      'run to the agent. Nothing was written. Pass --signing-key <owner key> with --as-owner, or drop the flag.'
    );
  }
  return undefined;
}

/** `--signing-key`, `NEXUS_VOTE_SIGNING_KEY` or "the agent key at <path>" — never the key bytes. */
function describeSource(signing: SigningOptions): string {
  switch (signing.source) {
    case 'flag':
      return '--signing-key';
    case 'env':
      return VOTE_SIGNING_KEY_ENV;
    case 'agent-default':
      return `the agent key at ${signing.keyPath}`;
  }
}

/** What `resolveSigning` needs beyond the flag and the environment. */
export interface ResolveSigningContext {
  /** `--as-owner` on this run. */
  readonly asOwner: boolean;
  /** The agent key's path; defaults to {@link agentSigningKeyPath}. Injected by tests so they never read `~`. */
  readonly agentKeyPath?: string;
}

/**
 * `--signing-key`, else `NEXUS_VOTE_SIGNING_KEY`, else the agent key when
 * its file exists, else unsigned. An empty env value is "not configured",
 * not a key at path ''. The allowed_signers is the one beside the ledger
 * being appended to. `--as-owner` with no key at all is a refusal at the
 * call site, not here: the attestation would be recorded nowhere.
 */
export function resolveSigning(
  flagKeyPath: string | undefined,
  env: NodeJS.ProcessEnv,
  ledgerPath: string,
  context: ResolveSigningContext
): SigningOptions | undefined {
  const allowedSignersPath = join(dirname(ledgerPath), ALLOWED_SIGNERS_FILE);
  const asOwner = context.asOwner;
  if (flagKeyPath !== undefined) {
    return { keyPath: flagKeyPath, allowedSignersPath, source: 'flag', asOwner };
  }
  const fromEnv = (env[VOTE_SIGNING_KEY_ENV] ?? '').trim();
  if (fromEnv !== '') return { keyPath: fromEnv, allowedSignersPath, source: 'env', asOwner };
  const agentKey = context.agentKeyPath ?? agentSigningKeyPath();
  if (existsSync(agentKey)) {
    return { keyPath: agentKey, allowedSignersPath, source: 'agent-default', asOwner };
  }
  return undefined;
}

/**
 * The one line the CLI prints after an append: the signer by principal and
 * kind (never the key), or the fact that no key was configured and the
 * three ways to configure one.
 */
export function signingNotice(
  signing: SigningState,
  record: SignableLedgerRecord,
  tool = 'append-ratification-record'
): string {
  if (signing === 'signed') {
    const principal = record.signature?.keyId ?? '(unknown)';
    return (
      `[${tool}] signed by ${principal} (${signerKindOf(principal)}; ` +
      `ssh-keygen -Y sign, namespace ${record.signature?.namespace ?? '?'}).`
    );
  }
  return (
    `[${tool}] appended UNSIGNED: no signing key configured ` +
    `(pass --signing-key <path>, set ${VOTE_SIGNING_KEY_ENV}, or generate the agent key with ` +
    `scripts/vote-record-keygen.ts at ${agentSigningKeyPath()}); the gate reports ` +
    'unsigned-record informationally until the #3927 phase-3 cutover.'
  );
}
