/**
 * nexus-agents/agents - Reasoning Module Exports
 *
 * Re-exports for Forest-of-Thought reasoning module.
 */

// Reasoning module (Forest-of-Thought)
export {
  // Node types
  type NodeId,
  type TreeId,
  type ForestId,
  type NodeState,
  type ReasoningStepType,
  type ReasoningNode,
  type ReasoningNodeMetadata,
  type CreateNodeInput,
  NodeStateSchema,
  ReasoningStepTypeSchema,
  ReasoningNodeMetadataSchema,
  ReasoningNodeSchema,
  // Tree types
  type TreeState,
  type PathScore,
  type PathScoreBreakdown,
  type PathScoringOptions,
  type TreeStatistics,
  type ReasoningTree,
  type CreateTreeInput,
  TreeStateSchema,
  PathScoreSchema,
  PathScoreBreakdownSchema,
  TreeStatisticsSchema,
  ReasoningTreeSchema,
  DEFAULT_PATH_SCORING_OPTIONS,
  // Configuration types
  type ActivationStrategy,
  type CrossTreeStrategy,
  type ForestPruningStrategy,
  type ForestConfig,
  type ActivationOptions,
  ActivationStrategySchema,
  CrossTreeStrategySchema,
  ForestPruningStrategySchema,
  ForestConfigSchema,
  DEFAULT_FOREST_CONFIG,
  DEFAULT_ACTIVATION_OPTIONS,
  // Forest types
  type ForestState,
  type SharedConclusion,
  type SharedInsight,
  type FailurePattern,
  type CrossTreeInfo,
  type ForestStatistics,
  type Forest,
  type CreateForestInput,
  ForestStateSchema,
  SharedConclusionSchema,
  SharedInsightSchema,
  FailurePatternSchema,
  CrossTreeInfoSchema,
  ForestStatisticsSchema,
  // Result types
  type TerminationReason,
  type BestSolution,
  type ExplorationEventType,
  type ExplorationEvent,
  type ForestResult,
  TerminationReasonSchema,
  BestSolutionSchema,
  ExplorationEventTypeSchema,
  ExplorationEventSchema,
  ForestResultSchema,
  // Engine (execution layer - Issue #513)
  ForestEngine,
  createForestEngine,
  executeForest,
  ForestExecutionError,
  ForestAdapterUnavailableError,
  type ForestEngineOptions,
} from './reasoning/index.js';
