name: Semgrep

on:
  pull_request: {}

permissions:
  contents: read
  security-events: write

jobs:
  scan:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Semgrep
        run: semgrep scan --config p/typescript --config p/nodejs --sarif > semgrep.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@bb471cdcf4dda2c934c5b656f554d43c1434ed13 # v4
        with:
          sarif_file: semgrep.sarif
        if: always()
