name: Semgrep

on:
  pull_request: {}

permissions:
  contents: read

jobs:
  scan:
    name: semgrep-oss/scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      security-events: write # SARIF upload
    container:
      image: semgrep/semgrep
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Semgrep
        run: semgrep scan --config p/typescript --config p/nodejs --sarif > semgrep.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@bb471cdcf4dda2c934c5b656f554d43c1434ed13 # v4
        with:
          sarif_file: semgrep.sarif
        if: always()
